baseurl = "https://jcos.io/"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.

# googleAnalytics = ""

disableFastRender = true

enableEmoji = "true"

[author]
  name = "John Cosio"

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Gaming and stuff on John Cosioâ€¦"
  keywords = "Homepage, Blog, Programming, Photoshop, Gaming, Gunpla"
  images = [""]

  # Homepage
  homeHeader = "Greetings traveller!"
  homeMessage1 = "Sit back, relax and play some games."
  homeMessage2 = "We can talk about work too."
  homeMessage3 = "How can I help you?"
  homeCTA1 = "Hang around"
  homeCTA2 = "Discuss work stuff"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = ["/css/styles.css", "/css/responsive.css"]
  customJS  = []

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Comments
  comments = "true"

  talkyardServerUrl = "https://comments-for-jcos-io.talkyard.net"
  talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"

  [params.logo]
    logoText     = "cd home/jcosio"
    logoHomeLink = "/"
    path         = "/images/logo.png"

  # Social icons
  [[params.social]]
    name = "backloggery"
    url  = "https://backloggery.com/sudoist"

  [[params.social]]
    name = "linkedin"
    url  = "https://ph.linkedin.com/in/johncosio"

  [[params.social]]
    name = "github"
    url  = "https://github.com/sudoist"

  [[params.social]]
    name = "unsplash"
    url  = "https://unsplash.com/@jcosio"

  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/channel/UCRHhhzP8dUEp_PS9eNUU2-A"

  [[params.social]]
    name = "email"
    url  = "mailto:mail@jcos.io"

[languages]
  [languages.en]
    title  = "John Cosio"
    subtitle  = "Gaming and stuff"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "project"
    name       = "Projects"
    url        = "/projects"

# Home CTA links
[home]
  [[menu.cta]]
    identifier = "project"
    name       = "-> Portfolio and work stuff"
    url        = "projects/"
  [[menu.cta]]
    identifier = "about"
    name       = "-> Learn more about what I do here"
    url        = "about/"
  [[menu.cta]]
    identifier = "gunpla/"
    name       = "-> See my little robots"
    url        = "categories/gunpla/"
